config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get 'review/index'

  get 'home/index'

  get 'checkout/new'

  devise_for :customers, :controllers => { registrations: 'registrations' }

  root 'home#index'
  get '/help-center' => 'home#helpcenter'
  get '/return-policy' => 'home#returnpolicy'


  resources :products do
    member do
      post 'favorites', to: 'products#add_to_favorites'
    end
    collection do
      get 'favorites'
    end
    resources :reviews, only: [:index, :create], defaults: {format: :json}
  end
  resources :order_lines, only: [:create, :update, :destroy]
  resource :checkouts, only: [:new, :create, :update]

  get 'prescription' => 'lens#enter_pre'
  get 'select_lens' => 'lens#select_len'
  get 'cities' => 'checkouts#cities'
  post 'prescription/create' => 'lens#create'
  patch 'prescription/update' => 'lens#update'
  patch 'prescription/update_pre' => 'lens#update_pre'
  delete 'prescription/destroy' => 'lens#destroy'


  get 'cart' => 'carts#show'
  get 'carts' => 'carts#index'

  get 'card' => 'checkouts#credit_card_info'
  post 'process_card' => 'checkouts#process_credit_card'

end

app/controllers/lens_controller.rb
class LensController < ApplicationController

  before_action :get_current_order_search

  def enter_pre

    @pre_type = [["Distance / Frames Only", "Distance / Frames Only"], ["Reading Lenses", "Reading Lenses"],
                 ["Bifocal Lenses", "Bifocal Lenses"], ["Progressive Lenses", "Progressive Lenses"]]

    session[:product_id] = params['product']

    @len_one = []
    (-15.00..6.00).step(0.25) do |n|
      @len_one << [n, n]
    end

    @cyl_one = []
    (-6.00..4.00).step(0.25) do |n|
      @cyl_one << [n, n]
    end

    @axis_one = []
    (1..180).each do |n|
      @axis_one << [n, n]
    end

    @add_one = []
    (1.00..3.00).step(0.25) do |n|
      @add_one << [n, n]
    end

    @pd_one = []
    (26..80).step(0.5) do |n|
      @pd_one << [n, n]
    end

    @pre_commit = false

    if session[:order_id] and Presciption.where(:product_id => session[:product_id], :order_id => session[:order_id].to_i).present?
      @pre = Presciption.where(:product_id => session[:product_id], :order_id => session[:order_id].to_i).last
    else
      if session[:pre_token]
        pres = Presciption.where(:pre_token => session[:pre_token])
        @pre = Presciption.find(pres.last.id)
      else
        @pre = Presciption.new
        @pre_commit = true
      end
    end
  end

  def create
    @pre = Presciption.new(prescription_params)
    if @pre.save
      session[:pre_token] = Digest::SHA1.hexdigest([Time.now, rand].join)
      @pre.pre_token = session[:pre_token]
      @pre.product_id = session[:product_id].to_i
      @product = Product.find(@pre.product_id)
      @pre.total_cost = @product.price
      @pre.total_cost = @pre.total_cost * @pre.qty
      @pre.save
      redirect_to select_lens_path
    else
      render :enter_pre
    end
  end

  def update

    if session[:order_id] and Presciption.where(:product_id => session[:product_id], :order_id => session[:order_id].to_i).present?
      @pre = Presciption.where(:product_id => session[:product_id], :order_id => session[:order_id].to_i).last
    else
      pres = Presciption.where(:pre_token => session[:pre_token])
      @pre = Presciption.find(pres.last.id)
    end
      @product = Product.find(@pre.product_id)
      if @pre.qty.nil?
        @pre.total_cost = @pre.total_cost * params[:presciption][:qty]
      else

        total_number = @pre.qty
        (0 .. total_number).each do
          @pre.total_cost = @pre.total_cost - @product.price
        end

        total_param_number = params[:presciption][:qty].to_f
        (0 .. total_param_number).each do
          @pre.total_cost = @pre.total_cost + @product.price
        end
      end
      @pre.save

      if @pre.update(prescription_params)
        redirect_to select_lens_path
      else
         flash.now[:alert] = @product.errors.full_messages.to_sentence
         render :enter_pre
      end

  end

  def select_len

    if session[:order_id] and Presciption.where(:product_id => session[:product_id], :order_id => session[:order_id].to_i).present?
      pres = Presciption.where(:product_id => session[:product_id], :order_id => session[:order_id].to_i)
    else
      pres = Presciption.where(:pre_token => session[:pre_token])
    end

    @pre = Presciption.find(pres.last.id)
    @product = Product.find(@pre.product_id)
  end

  def update_pre

    if session[:order_id] and Presciption.where(:product_id => session[:product_id], :order_id => session[:order_id].to_i).present?
      @pre = Presciption.where(:product_id => session[:product_id], :order_id => session[:order_id].to_i).last
    else
      pres = Presciption.where(:pre_token => session[:pre_token])
      @pre = Presciption.find(pres.last.id)
    end
        @pre.update(prescription_params)
        @order = current_order
        @pre.order_id =  @order.id
        @pre.save
        session[:order_id] = @order.id

        session[:pre_token] = nil
        redirect_to cart_path
  end

  def destroy
    @order = current_order
    @order_line = @order.presciptions.find(params[:id])
    @order_line.destroy
    session[:pre_token] = nil
    flash[:success] = I18n.t("item_removed")
    redirect_to cart_path
  end

  private

  def prescription_params
    params.require(:presciption).permit(:sphere, :cylinder, :axis, :add, :pd,
                                         :sphere_right, :cylinder_right,:axis_right, :lense_type, :add_right,:pd_right,
                                         :customer_id, :pre_token, :pre_type, :total_cost, :qty, :protective_coating,
                                         :scratch_resistant_coating, :anti_reflective_coating, :cost)
  end

end

app/helpers/lens_helper.rb
module LensHelper
end

app/views/lens/_create.html.erb
<div class="mainWrapper">
  <section class="internalBanner">
  </section>
  <%= form_for @pre , url: prescription_create_path do |f| %>
      <div class="productDetailWrapper">
        <div class="container">
          <div class="clearfix stepsWrapper">
            <span class="stepCir pull-left active">1</span>
            <h3 class="pull-left" style="color: #000000">Your Prescription</h3>
            <span class="stepCir pull-right">2</span>
            <div class="border-bg"></div>
          </div>

          <section class="productInfoWrap">
            <div class="prescDropWrap" style="width: 556px;">
              <label for="typ">Type:</label>
              <%= f.select(:pre_type, options_for_select(@pre_type, id: "typ")) %>

              <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="What kind of eyeglasses do you need?">?</button>
            </div>


            <div class="prescDropWrap"  style="width: 250px;">
              <label for="qty">qty:</label>
              <%= f.select(:qty, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10]])) %>
              <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Quantity of the product">?</button>
            </div>

          </section>

          <section class="productInfoWrap">
            <div class="clearfix">
              <div class="cusColFourth">
                <h3 class="form-title">OD (Left)</h3>
                <div class="prescDropWrap">
                  <label for="sph">SPH</label>
                  <%= f.select(:sphere, options_for_select(@len_one, id: "sph")) %>

                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Sphere (SPH). is the amount of lens power, measured in diopters (D), prescribed to correct nearsightedness or farsightedness. If the number appearing under this heading has a minus sign (–), you are nearsighted; if the number has a plus sign (+) or is not preceded by a plus sign or a minus sign, you are farsighted. Make sure to select the correct sign (+/-) while ordering.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="cyl">cyl</label>
                  <%= f.select(:cylinder, options_for_select(@cyl_one, id: "cyl")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Cylinder (CYL). is the amount of lens power for astigmatism. If nothing appears in this column, you have no astigmatism and you can leave it blank. Make sure to select the correct sign (+/-) while ordering">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="axis">axis</label>
                  <%= f.select(:axis, options_for_select(@axis_one, id: "axis")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Axis describes the lens meridian that contains no cylinder power to correct astigmatism. The axis is defined with a number from 1 to 180. If an eyeglass prescription includes cylinder power, it also must include an axis value, which follows the cyl power and is preceded by an 'x' when written freehand.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="add">add</label>
                  <%= f.select(:add, options_for_select(@add_one, id: "add")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="ADD. is the added magnifying power applied to the bottom part of multifocal lenses to correct reading vision. The number appearing in this section of the prescription is always a 'plus' power, even if it is not preceded by a plus sign. Generally, it will range from +1.00 to +3.00.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="pd">pd</label>
                  <%= f.select(:pd, options_for_select(@pd_one, id: "pd")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="

PD is the distance between your pupils. Usually,  it ranges from 57 to 65 mm. It is highly recommended to get your PD from your optometrist if you have a high power or if you are going to order bifocal, progressive or computer lenses.">?</button>
                </div>
              </div>
              <div class="cusColFourth">
                <h3 class="form-title">OD (Right)</h3>
                <div class="prescDropWrap">
                  <label for="sph">SPH</label>
                  <%= f.select(:sphere_right, options_for_select(@len_one, id: "sph")) %>

                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Sphere (SPH). is the amount of lens power, measured in diopters (D), prescribed to correct nearsightedness or farsightedness. If the number appearing under this heading has a minus sign (–), you are nearsighted; if the number has a plus sign (+) or is not preceded by a plus sign or a minus sign, you are farsighted. Make sure to select the correct sign (+/-) while ordering.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="cyl">cyl</label>
                  <%= f.select(:cylinder_right, options_for_select(@cyl_one, id: "cyl")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Cylinder (CYL). is the amount of lens power for astigmatism. If nothing appears in this column, you have no astigmatism and you can leave it blank. Make sure to select the correct sign (+/-) while ordering">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="axis">axis</label>
                  <%= f.select(:axis_right, options_for_select(@axis_one, id: "axis")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Axis describes the lens meridian that contains no cylinder power to correct astigmatism. The axis is defined with a number from 1 to 180. If an eyeglass prescription includes cylinder power, it also must include an axis value, which follows the cyl power and is preceded by an 'x' when written freehand.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="add">add</label>
                  <%= f.select(:add_right, options_for_select(@add_one, id: "add")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="ADD. is the added magnifying power applied to the bottom part of multifocal lenses to correct reading vision. The number appearing in this section of the prescription is always a 'plus' power, even if it is not preceded by a plus sign. Generally, it will range from +1.00 to +3.00.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="pd">pd</label>
                  <%= f.select(:pd_right, options_for_select(@pd_one, id: "pd")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="PD is the distance between your pupils. Usually,  it ranges from 57 to 65 mm. It is highly recommended to get your PD from your optometrist if you have a high power or if you are going to order bifocal, progressive or computer lenses.">?</button>
                </div>
              </div>
            </div>
            <div class="selectLensWrap">
              <a class="btn btn-default" href="#" onclick="openPrevProduct('<%= session[:product_id] %>')">Back</a>
              <%= f.submit "Select Lens", class: "btn btn-primary" %>
            </div>
          </section>
        </div>
      </div>
  <% end %>
</div>

app/views/lens/_update.html.erb
<div class="mainWrapper">
  <section class="internalBanner">
  </section>
  <%= form_for @pre , url: prescription_update_path, method: "PATCH" do |f| %>
      <div class="productDetailWrapper">
        <div class="container">
          <div class="clearfix stepsWrapper">
            <span class="stepCir pull-left active">1</span>
            <h3 class="pull-left" style="color: #000000">Your Prescription</h3>
            <span class="stepCir pull-right">2</span>
            <div class="border-bg"></div>
          </div>

          <section class="productInfoWrap">
            <div class="prescDropWrap"  style="width: 556px;">
              <label for="typ">Type:</label>
              <%= f.select(:pre_type, options_for_select(@pre_type, :selected => @pre.pre_type)) %>

              <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="What kind of eyeglasses do you need?">?</button>
            </div>


            <div class="prescDropWrap"  style="width: 250px;">
              <label for="qty">qty:</label>
              <%= f.select(:qty, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10]], :selected => @pre.qty)) %>
              <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Quantity of the product">?</button>
            </div>

          </section>



          <section class="productInfoWrap">
            <div class="clearfix">
              <div class="cusColFourth">
                <h3 class="form-title">OD (Left)</h3>
                <div class="prescDropWrap">
                  <label for="sph">SPH</label>
                  <%= f.select(:sphere, options_for_select(@len_one, :selected => @pre.sphere)) %>

                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Sphere (SPH). is the amount of lens power, measured in diopters (D), prescribed to correct nearsightedness or farsightedness. If the number appearing under this heading has a minus sign (–), you are nearsighted; if the number has a plus sign (+) or is not preceded by a plus sign or a minus sign, you are farsighted. Make sure to select the correct sign (+/-) while ordering.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="cyl">cyl</label>
                  <%= f.select(:cylinder, options_for_select(@cyl_one, id: "cyl")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Cylinder (CYL). is the amount of lens power for astigmatism. If nothing appears in this column, you have no astigmatism and you can leave it blank. Make sure to select the correct sign (+/-) while ordering">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="axis">axis</label>
                  <%= f.select(:axis, options_for_select(@axis_one, id: "axis")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Axis describes the lens meridian that contains no cylinder power to correct astigmatism. The axis is defined with a number from 1 to 180. If an eyeglass prescription includes cylinder power, it also must include an axis value, which follows the cyl power and is preceded by an 'x' when written freehand.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="add">add</label>
                  <%= f.select(:add, options_for_select(@add_one, id: "add")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="ADD. is the added magnifying power applied to the bottom part of multifocal lenses to correct reading vision. The number appearing in this section of the prescription is always a 'plus' power, even if it is not preceded by a plus sign. Generally, it will range from +1.00 to +3.00.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="pd">pd</label>
                  <%= f.select(:pd, options_for_select(@pd_one, id: "pd")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="

PD is the distance between your pupils. Usually,  it ranges from 57 to 65 mm. It is highly recommended to get your PD from your optometrist if you have a high power or if you are going to order bifocal, progressive or computer lenses.">?</button>
                </div>
              </div>
              <div class="cusColFourth">
                <h3 class="form-title">OD (Right)</h3>
                <div class="prescDropWrap">
                  <label for="sph">SPH</label>
                  <%= f.select(:sphere_right, options_for_select(@len_one, id: "sph")) %>

                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Sphere (SPH). is the amount of lens power, measured in diopters (D), prescribed to correct nearsightedness or farsightedness. If the number appearing under this heading has a minus sign (–), you are nearsighted; if the number has a plus sign (+) or is not preceded by a plus sign or a minus sign, you are farsighted. Make sure to select the correct sign (+/-) while ordering.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="cyl">cyl</label>
                  <%= f.select(:cylinder_right, options_for_select(@cyl_one, id: "cyl")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Cylinder (CYL). is the amount of lens power for astigmatism. If nothing appears in this column, you have no astigmatism and you can leave it blank. Make sure to select the correct sign (+/-) while ordering">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="axis">axis</label>
                  <%= f.select(:axis_right, options_for_select(@axis_one, id: "axis")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="Axis describes the lens meridian that contains no cylinder power to correct astigmatism. The axis is defined with a number from 1 to 180. If an eyeglass prescription includes cylinder power, it also must include an axis value, which follows the cyl power and is preceded by an 'x' when written freehand.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="add">add</label>
                  <%= f.select(:add_right, options_for_select(@add_one, id: "add")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="ADD. is the added magnifying power applied to the bottom part of multifocal lenses to correct reading vision. The number appearing in this section of the prescription is always a 'plus' power, even if it is not preceded by a plus sign. Generally, it will range from +1.00 to +3.00.">?</button>
                </div>
                <div class="prescDropWrap">
                  <label for="pd">pd</label>
                  <%= f.select(:pd_right, options_for_select(@pd_one, id: "pd")) %>
                  <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="right" title="PD is the distance between your pupils. Usually,  it ranges from 57 to 65 mm. It is highly recommended to get your PD from your optometrist if you have a high power or if you are going to order bifocal, progressive or computer lenses.">?</button>
                </div>
              </div>
            </div>
            <div class="selectLensWrap">
              <a class="btn btn-default" href="#" onclick="openPrevProduct('<%= session[:product_id] %>')">Back</a>
              <%= f.submit "Select Lens", class: "btn btn-primary" %>
            </div>
          </section>
        </div>
      </div>
  <% end %>
</div>

app/views/lens/enter_pre.html.erb
<% if @pre_commit %>
    <%= render 'lens/create' %>
<% else %>
    <%= render 'lens/update' %>
<% end %>

app/views/lens/select_len.html.erb
<div class="mainWrapper">
  <section class="internalBanner">
  </section>
  <%= form_for @pre , url: prescription_update_pre_path do |f| %>
  <div class="productDetailWrapper">
    <div class="container">
      <div class="clearfix stepsWrapper stepsActive">
        <span class="stepCir pull-left active">1</span>
        <span class="stepCir pull-left active">2</span>
        <h3 class="pull-left">Lenses and Coatings</h3>
        <div class="border-bg"></div>
      </div>
      <section class="productInfoWrap">
        <div class="row">
          <div class="col-md-12">
            <h3 class="form-subtitle">Lenses</h3>
          </div>
          <div class="col-md-4">
            <div class="lensCotingPriceBox" data-container="body" data-toggle="popover"
                 data-placement="bottom" data-content="- High Quality Single Vision 1.50 Index prescription lenses<br>- Recomended RX range: -1.00 + 1.00<br>- 40% to 60% saving from traditional glasses
  retailer ($170)" data-trigger="hover" data-html="true">
              <div class="radioCheckWrap">
                <%= f.radio_button :lense_type, "1.5 Index Standard Lenses", id: "lcp1" %>
                <label for="lcp1"><span>Free</span></label>
              </div>
              <div class="imgShowCase">
                <%= image_tag('glass1.png', :class => "img-responsive") %>
                <h5>
                  <strong>Standard Lenses</strong>
                  (1.5 Index)
                </h5>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="lensCotingPriceBox" data-container="body" data-toggle="popover"
                 data-placement="bottom" data-content="- High Quality Single Vision 1.50 Index prescription lenses<br>- Recomended RX range: -1.00 + 1.00<br>- 40% to 60% saving from traditional glasses
  retailer ($170)" data-trigger="hover" data-html="true">
              <div class="radioCheckWrap">
                <%= f.radio_button :lense_type, "1.61 High Index lenses", id: "lcp2" %>
                <label for="lcp2"><span>+$9.95</span></label>
              </div>
              <div class="imgShowCase">
                <%= image_tag('glass1.png', :class => "img-responsive") %>
                <h5>
                  <strong>High Index Lenses</strong>
                  (1.61 Index)
                </h5>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="lensCotingPriceBox" data-container="body" data-toggle="popover"
                 data-placement="bottom" data-content="- High Quality Single Vision 1.50 Index prescription lenses<br>- Recomended RX range: -1.00 + 1.00<br>- 40% to 60% saving from traditional glasses
  retailer ($170)" data-trigger="hover" data-html="true">
              <div class="radioCheckWrap">
                <%= f.radio_button :lense_type, "1.67 High Index lenses", id: "lcp3" %>
                <label for="lcp3"><span>+$29.95</span></label>
              </div>
              <div class="imgShowCase">
                <%= image_tag('glass1.png', :class => "img-responsive") %>
                <h5>
                  <strong>High Index Lenses</strong>
                  (1.67 Index)
                </h5>
              </div>
            </div>
          </div>
        </div>
        <div class="row coatingWrapper">
          <div class="col-md-12">
            <h3 class="form-subtitle">Coatings</h3>
          </div>
          <div class="col-md-4">
            <div class="coatingInfoBox">
              <div class="radioCheckWrap">
                <%= f.check_box :protective_coating, id: "cw1" %>
                <label for="cw1"><span>$9.95</span></label>
              </div>
              <p>
                <strong>UV Protective Coating</strong>
                <span>UV Protective Coating shields your
                                    eyes form harmful UV rays.</span>
              </p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="coatingInfoBox">
              <div class="radioCheckWrap">
                <%= f.check_box :scratch_resistant_coating, id: "cw2" %>
                <label for="cw2"><span>$9.95</span></label>
              </div>
              <p>
                <strong>Scratch Resistant Coating</strong>
                <span>Scratch Resistant Coating minimizes the occurence of minor scratches on the surface and improves the durability the lenses.</span>
              </p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="coatingInfoBox">
              <div class="radioCheckWrap">
                <%= f.check_box :anti_reflective_coating, id: "cw3" %>
                <label for="cw3"><span>$9.95</span></label>
              </div>
              <p>
                <strong>Anti Reflective Coating</strong>
                <span>Anti Reflective Coating reduces glares and minimizes eye strain. This coating is important for extended computer use and nighttime driving</span>
              </p>
            </div>
          </div>
        </div>
        <div class="priceStaticWrapper clearfix">
          <strong class="pull-right"><sup>$</sup><strong id="price-change" ><%= @pre.total_cost %></strong></strong>
        </div>
        <%= f.hidden_field :total_cost %>
        <div class="selectLensWrap">
          <a class="btn btn-default" href="#" onclick="openPrevPre()">Back</a>
          <%= f.submit "Add to Cart", class: "btn btn-primary", :onclick => "pres_selection(event)" %>
        </div>

      </section>
    </div>
  </div>
</div>
<% end %>
<!--home page end-->