config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get 'review/index'

  get 'home/index'

  get 'checkout/new'

  devise_for :customers, :controllers => { registrations: 'registrations' }

  root 'home#index'
  get '/help-center' => 'home#helpcenter'
  get '/return-policy' => 'home#returnpolicy'


  resources :products do
    member do
      post 'favorites', to: 'products#add_to_favorites'
    end
    collection do
      get 'favorites'
    end
    resources :reviews, only: [:index, :create], defaults: {format: :json}
  end
  resources :order_lines, only: [:create, :update, :destroy]
  resource :checkouts, only: [:new, :create, :update]

  get 'prescription' => 'lens#enter_pre'
  get 'select_lens' => 'lens#select_len'
  get 'cities' => 'checkouts#cities'
  post 'prescription/create' => 'lens#create'
  patch 'prescription/update' => 'lens#update'
  patch 'prescription/update_pre' => 'lens#update_pre'
  delete 'prescription/destroy' => 'lens#destroy'


  get 'cart' => 'carts#show'
  get 'carts' => 'carts#index'

  get 'card' => 'checkouts#credit_card_info'
  post 'process_card' => 'checkouts#process_credit_card'

end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  require "uri"
  require "net/http"

  before_action :get_current_order_search, except: :cities

  def new
   # qwert = OrderNotifier.send_order_email(current_order).deliver
    if current_order.shipping_address
      @address = current_order.shipping_address
    else
      @address = ShippingAddress.new
    end
  end

  def create
    @address = ShippingAddress.new(address_params)
    if @address.save
      @address.order_id = session[:order_id]
      @address.save
      session[:address_id] = @address.id
      @order = Order.find(current_order)
      @order.update(:status => 1)
      redirect_to card_path
    else
      flash.now[:alert] = @address.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    @address = ShippingAddress.find(session[:address_id])
    @address = @address.update(address_params)
    @order = Order.find(current_order)
    @order.update(:status => 1)
    redirect_to card_path
  end

  def credit_card_info
    @order = current_order
  end

  def process_credit_card
    uri = URI.parse("http://localhost:3001/api/v1/dummy_gateway")
    response = Net::HTTP.post_form(uri, params)
    data = JSON.parse(response.body).first[1]
    if response.code == "200"
      flash[:success] = data
    else
      flash[:alert] = data
    end
    redirect_to cart_path
  end

  def cities
    @cities = CS.cities(params["country_id"], :ca)
    render json: @cities
  end

  private
  def address_params
    params.require(:shipping_address).permit(:customer_id,:first_name, :last_name, :email, :country, :province, :city,
                                             :address, :postal_code, :phone_number, :shipping_address,:shipping_country,
                                             :shipping_province,:shipping_city,:shipping_postal_code)
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkouts/_form.html.erb
<%= form_for @address, :url => url_for(:controller => 'checkouts', :action => 'create'),
             :html => { :class => "form-horzontal" } do |f| %>
    <fieldset>

      <div class="col-lg-12 form-group margin50">
        <%= f.label :address, class: "col-lg-2" %>
        <div class="col-lg-4">
          <%= f.text_area :address, class: "form-control name" %>
        </div>
      </div>

      <div class="col-lg-12 form-group margin50">
        <%= f.label :phone_number, class: "col-lg-2" %>
        <div class="col-lg-4">
          <%= f.text_field :phone_number, class: "form-control name" %>
        </div>
      </div>
      <%= f.hidden_field :customer_id, value: current_customer.id %>


      <div class="col-lg-12 form-group margin50">
        <div class="col-lg-4">
          <%= f.submit "Submit", class:"btn btn-lg btn-primary btn-block custom-button" %>
        </div>
      </div>


    </fieldset>
<% end %>

app/views/checkouts/credit_card_info.html.erb
<%= form_tag(process_card_path, :method=>'post') do %>
    <%= render 'checkouts/card' %>
<% end %>

app/views/checkouts/new.html.erb
<div class="mainWrapper">
  <section class="internalBanner">
  </section>
  <%= form_for @address , url: checkouts_path  do |f| %>
  <div class="productDetailWrapper">
    <div class="container">
      <section class="prodBilling">
        <div class="PersonDetailWrapper">
          <div class="clearfix">
        <div class="cusColFourth">
        <h3 class="page-title">Billing Address</h3>

          <div class="form-group">
            <label for="first-name">First Name<span class="error-class">*</span></label>
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="last-name">Last Name<span class="error-class">*</span></label>
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="email">Email<span class="error-class">*</span></label>
            <%= f.text_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="country">Country</label>
            <%= f.select(:country, options_for_select([["Canada","Canada"]])) %>
          </div>
          <div class="form-group">
            <label for="province">State</label>
            <%= f.select(:province, options_for_select(CS.states(:ca))) %>

          </div>
          <div class="form-group">
            <label for="city">City</label>
            <%= f.select(:city, options_for_select(CS.cities(:AB, :ca))) %>
          </div>
          <div class="form-group">
            <label for="add1">Address<span class="error-class">*</span></label>
            <%= f.text_field :address, class: "form-control name" %>
          </div>
          <div class="form-group">
            <label for="pc">Postal Code<span class="error-class">*</span></label>
            <%= f.text_field :postal_code, class: "form-control name", :placeholder => "K1A0A6"  %>
          </div>
          <div class="form-group">
            <label for="phnumb">Phone Number<span class="error-class">*</span></label>
            <%= f.text_field :phone_number, class: "form-control name", :placeholder => "14165096995" %>
          </div>

          </div>

        <div class="cusColFourth">
          <h3 class="page-title">Shipping Address</h3>
          <div class="form-group">
            <label for="add1">Address<span class="error-class">*</span></label>
            <%= f.text_field :shipping_address, class: "form-control name" %>
          </div>
          <div class="form-group">
            <label for="country">Country</label>
            <%= f.select(:shipping_country, options_for_select([["Canada","Canada"]])) %>
          </div>
          <div class="form-group">
            <label for="province">Province</label>
            <%= f.select(:shipping_province, options_for_select(CS.states(:ca))) %>
          </div>
          <div class="form-group">
            <label for="city">City</label>
            <%= f.select(:shipping_city, options_for_select(CS.cities(:AB, :ca))) %>
          </div>
          <div class="form-group">
            <label for="pc">Postal Code<span class="error-class">*</span></label>
            <%= f.text_field :shipping_postal_code, class: "form-control name", :placeholder => "K1A0A6" %>
          </div>
        </div>
          </div>
          </div>

        <br />
          <div class="row">
          <div class="form-group">
            <div class="radioCheckWrap">
              <input type="checkbox" id="cnf1" name="cnf1"/>
              <label for="cnf1"><span>My billing address is the same as shipping address.</span> </label>
            </div>
          </div>

        <div class="selectLensWrap">
          <%= f.submit "Proceed to Payment", class:"btn btn-primary" %>
        </div>
          </div>
      </section>


    </div>


  </div>

  <% end %>
</div>