config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get 'review/index'

  get 'home/index'

  get 'checkout/new'

  devise_for :customers, :controllers => { registrations: 'registrations' }

  root 'home#index'
  get '/help-center' => 'home#helpcenter'
  get '/return-policy' => 'home#returnpolicy'


  resources :products do
    member do
      post 'favorites', to: 'products#add_to_favorites'
    end
    collection do
      get 'favorites'
    end
    resources :reviews, only: [:index, :create], defaults: {format: :json}
  end
  resources :order_lines, only: [:create, :update, :destroy]
  resource :checkouts, only: [:new, :create, :update]

  get 'prescription' => 'lens#enter_pre'
  get 'select_lens' => 'lens#select_len'
  get 'cities' => 'checkouts#cities'
  post 'prescription/create' => 'lens#create'
  patch 'prescription/update' => 'lens#update'
  patch 'prescription/update_pre' => 'lens#update_pre'
  delete 'prescription/destroy' => 'lens#destroy'


  get 'cart' => 'carts#show'
  get 'carts' => 'carts#index'

  get 'card' => 'checkouts#credit_card_info'
  post 'process_card' => 'checkouts#process_credit_card'

end

app/models/product.rb
class Product < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader
  mount_uploader :secavatar, SecavatarUploader
  mount_uploader :thirdavatar, ThirdavatarUploader
  mount_uploader :fourthavatar, FourthavatarUploader
  mount_uploader :fifthavatar, FifthavatarUploader
  mount_uploader :sixthavatar, SixthavatarUploader
  mount_uploader :seventhavatar, SeventhavatarUploader
  mount_uploader :eighthavatar, EighthavatarUploader
  mount_uploader :ninthavatar, NinthavatarUploader
  mount_uploader :tenthavatar, TenthavatarUploader
  mount_uploader :itemspec, ItemspecUploader




  has_many :order_lines
  has_many :reviews
  has_many :presciptions

  scope :is_enabled, -> { where(status: true) }

  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 1.0 }
  validates :name, uniqueness: true

  scope :with_category, lambda { |flag|
    where(category:[*flag])
  }

  def rating=(value)
    @rating = value
  end

  def rating
    @rating = Review.average_rating(id)
    @rating ? @rating.to_i : 0
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :get_current_order_search
  require 'will_paginate/array'

  def index

    if params["sort"] == "asc"
      @q.sorts = "price asc"
    elsif params["sort"] == "dec"
      @q.sorts = "price dec"
    end

    begin
      if params["q"]["category_in"].length == 1
        if params["q"]["category_in"][0] == "men"
          @page_title = """Men's"""
        elsif params["q"]["category_in"][0] == "women"
           @page_title = """Women's"""
        elsif params["q"]["category_in"][0] == "kids"
            @page_title = """Kid's"""
        else
            @page_title = """Any"""
        end
      else
        @page_title = """Any"""
      end
    rescue
      @page_title = """Any"""
    end


    @products = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 12)
    @fav_list = false


    respond_to do |format|
        format.html
        format.json
        format.js { render 'products/paginate' }
    end
  end

  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = I18n.t("product_created")
      redirect_to products_path
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
     @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = I18n.t("product_edit")
      redirect_to products_path
    else
      flash.now[:alert] = @product.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.presciptions.each do |i|
      i.destroy
    end
    Product.find(params[:id]).destroy
    redirect_to admin_products_path
  end

  def add_to_favorites
    (session[:favorite_products] ||= []) << params[:id]
    render json: {msg: 'successfully added to favorites'}
  end

  def favorites
    @page_title = """Your Wishlist"""
    @fav_list = true
    begin
      @products = Product.find(session[:favorite_products] || []).paginate(:page => params[:page], :per_page => 12)
    rescue
      @products = Product.find([]).paginate(:page => params[:page], :per_page => 12)
    end
    @q = Product.search(params[:q])
    render :index
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :status, :avatar, :secavatar,
                                    :thirdavatar, :fourthavatar,
                                    :fifthavatar, :sixthavatar,
                                    :seventhavatar, :eighthavatar,
                                    :ninthavatar, :tenthavatar, :itemspec, :category, :subcategory, :newarrivals,
                                    :bestselling, :popularbrand, :brand, :frames, :shapes,
                                    :material, :size, :color, :rx_type)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="mainWrapper">
  <section class="internalBanner">
  </section>

  <div class="productDetailWrapper">
    <div class="container">
      <div class="clearfix stepsWrapper">
        <span class="stepCir pull-left">1</span>
        <h3 class="pull-left">Your Prescription</h3>
        <span class="stepCir pull-right">2</span>
        <div class="border-bg"></div>
      </div>
      <section class="productInfoWrap">
        <div class="row">
          <div class="col-md-9">
            <div class="prodCarouselWrapper">
              <div class="productDescWrap">
                <div class="glassInfoWrap">
                  <%= image_tag(@product.secavatar, :class => "img-responsive") %>
                </div>
                <div class="glassInfoWrap">
                  <%= image_tag(@product.thirdavatar, :class => "img-responsive") %>
                </div>
                <div class="glassInfoWrap">
                  <%= image_tag(@product.fourthavatar, :class => "img-responsive") %>
                </div>
                <div class="glassInfoWrap">
                  <%= image_tag(@product.fifthavatar, :class => "img-responsive") %>
                </div>
                <div class="glassInfoWrap">
                  <%= image_tag(@product.sixthavatar, :class => "img-responsive") %>
                </div>
                <div class="glassInfoWrap">
                  <%= image_tag(@product.seventhavatar, :class => "img-responsive") %>
                </div>
                <div class="glassInfoWrap">
                  <%= image_tag(@product.eighthavatar, :class => "img-responsive") %>
                </div>
                <div class="glassInfoWrap">
                  <%= image_tag(@product.ninthavatar, :class => "img-responsive") %>
                </div>
                <div class="glassInfoWrap">
                  <%= image_tag(@product.tenthavatar, :class => "img-responsive") %>
                </div>
              </div>
              <div class="slider-nav">
                <div>
                  <%= image_tag(@product.secavatar, :class => "img-responsive") %>
                </div>
                <div>
                  <%= image_tag(@product.thirdavatar, :class => "img-responsive") %>
                </div>
                <div>
                  <%= image_tag(@product.fourthavatar, :class => "img-responsive") %>
                </div>
                <div>
                  <%= image_tag(@product.fifthavatar, :class => "img-responsive") %>
                </div>
                <div>
                  <%= image_tag(@product.sixthavatar, :class => "img-responsive") %>
                </div>
                <div>
                  <%= image_tag(@product.seventhavatar, :class => "img-responsive") %>
                </div>
                <div>
                  <%= image_tag(@product.eighthavatar, :class => "img-responsive") %>
                </div>
                <div>
                  <%= image_tag(@product.ninthavatar, :class => "img-responsive") %>
                </div>
                <div>
                  <%= image_tag(@product.tenthavatar, :class => "img-responsive") %>
                </div>
              </div>
            </div>
            <div class="itemSpecsWrapper">
              <div class="row">
                <div class="col-sm-6">
                  <div class="itemSpecs clearfix">
                    <span>Eligible for Progressive</span>
                    <strong>yes</strong>
                  </div>
                  <div class="itemSpecs clearfix">
                    <span>Material</span>
                    <strong><%= @product.material %></strong>
                  </div>
                  <div class="itemSpecs clearfix">
                    <span>Gender</span>
                    <strong>unisex</strong>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="imgWrap">
                    <%= image_tag(@product.itemspec, :class => "img-responsive") %>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="productSidebar">
              <h3><%= @product.name %><br></h3>
              <h4>
               <!-- <span>$179.00</span> -->
                <%= number_to_currency(@product.price) %>
              </h4>
              <div class="descProd">
                <%= @product.description %>
                <div class="ratingSocialWrap">
                  <%= text_field_tag @product.id, @product.rating, class: 'custum-star-rating' %>
                  <span class="socialWrap">
                      <%= link_to favorites_product_path(@product), method: :post, :remote => true do %>
                        <i class="fa fa-heart" aria-hidden="true"></i>
                      <% end %>
                  </span>

                </div>
              </div>
              <div id="share"></div>

              <% if @product.size == 'small' %>
                  <div class="selectLensWrap2">
                    <p>Sizes:</p>
                    <a>S</a>
                  </div>
              <% end %>

              <% if @product.size == 'medium' %>
                  <div class="selectLensWrap2">
                    <p>Sizes:</p>
                    <a>M</a>
                  </div>
              <% end %>

              <% if @product.size == 'large' %>
                  <div class="selectLensWrap2">
                    <p>Sizes:</p>
                    <a>L</a>
                  </div>
              <% end %>


              <div class="selectLensWrap" style="margin-top: 5px !important">

                <%= link_to "Buy with Prescription", prescription_path(:product => @product.id), method: :get, class: "btn btn-primary button-width" %>
              </div>
              <div class="helpCenterWrapper">
                <div class="helpbox2">
                  <p style="margin-top: 5px"><i class="fa fa-check" aria-hidden="true"></i>
                    <b>Free Shipping</b> - ships within 5 to 10 days</p>
                  <p><i class="fa fa-check" aria-hidden="true"></i> 24 months warranty</p>
                  <p><i class="fa fa-check" aria-hidden="true"></i>
                    <b>Lenses</b> - for all Eyewear needs</p>


                </div>

              </div>

            </div>
          </div>
        </div>

      </section>
    </div>
  </div>
</div>

app/views/products/_products.html.erb
<div id="filterrific_results">

<div class="row">
  <% for product in @products %>
      <div class="col-md-3">
        <div class="glassInfoWrap">
          <span class="price"><%= number_to_currency(product.price) %></span>
          <%= image_tag(product.avatar, :class => "img-responsive") %>
          <div class="ratingSocialWrap">
            <fieldset class="rating">
              <input type="radio" id="naw_star5" name="rating" value="5"/><label
            class="full"
            for="naw_star5"></label>
              <input type="radio" id="naw_star4" name="rating" value="4"/><label
            class="full"
            for="naw_star4"></label>
              <input type="radio" id="naw_star3" name="rating" value="3"/><label
            class="full"
            for="naw_star3"></label>
              <input type="radio" id="naw_star2" name="rating" value="2"/><label
            class="full"
            for="naw_star2"></label>
              <input type="radio" id="naw_star1" name="rating" value="1"/><label
            class="full"
            for="naw_star1"></label>
            </fieldset>
            <span class="socialWrap">
                                        <a href="javascript:">
                                            <i class="fa fa-share-alt" aria-hidden="true"></i>
                                        </a>
                                        <a href="javascript:">
                                            <i class="fa fa-heart" aria-hidden="true"></i>
                                        </a>
                                        <a href="javascript:">
                                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                        </a>
                                    </span>
          </div>
        </div>
      </div>
  <% end %>
</div>
</div>

app/views/products/_show.html.erb
<div class="row">
  <% for product in @products %>
      <div class="col-md-3">
        <div class="glassInfoWrap">
          <h4 class="list-group-item-heading"></h4>
          <span class="price"><%= number_to_currency(product.price) %></span>

          <%= link_to product,  { 'data-toggle' => "tooltip", 'data-placement' => "top", 'title' => product.name, 'data-method' => 'get' }  do %>
              <%= image_tag(product.avatar, :class => "img-responsive") %>
          <% end %>

          <div class="ratingSocialWrap">
            <%= text_field_tag product.id, product.rating, class: 'custum-star-rating' %>
            <span class="socialWrap">
                      <%= link_to favorites_product_path(product), method: :post, :remote => true do %>
                        <i class="fa fa-heart" aria-hidden="true"></i>
                      <% end %>
              <%= link_to prescription_path(:product => product.id), method: :get do %>
                          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        <% end %>
                  </span>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<!--<div  class="wrapper-product-list">
  <h1>Products</h1>
  <div class="list-group">
    <% if @products.present? %>
        <%= render 'products/products' %>
    <% else %>
        <p>Sorry, no products listed yet</p>
    <% end %>
    </div>
</div>-->
<div class="mainWrapper">
  <section class="internalBanner">
  </section>
  <div class="mainFilterWrapper">
    <div class="filterWrapper">
      <div class="container">
        <ul class="filterCat">
          <li class="filterLegend">
            <a id="filterMenuBtn" href="javascript:void(0)">
              <div class="bars">
                <span></span>
                <span></span>
                <span></span>
              </div>
              Filter
            </a>
            <span>Price</span>
          </li>
          <li>Gender</li>
          <li>Frames</li>
          <li>Shapes</li>
          <li>Material</li>
          <li>Size</li>
          <li>Color</li>
          <li>RX Type</li>
        </ul>
      </div>
    </div>
    <%= search_form_for @q , url: products_path do |f| %>
    <div class="filterOptions">
      <div class="container">
        <ul>
          <li data-legend="Price">
            <div id="nonlinear"></div>
            <span id="slider-margin-value-min"></span>
            <span id="slider-margin-value-max"></span>
            <%= f.hidden_field :price_gteq %>
            <%= f.hidden_field :price_lteq %>
          </li>

          <li data-legend="Gender">
            <div class="radioCheckWrap">
              <%= check_box_tag('q[category_in][]', 'men', nil, :id => "c1" ) %>
              <label for="c1"><span>Men's</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[category_in][]', 'women', nil, :id => "c2" ) %>
              <label for="c2"><span>Women's</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[category_in][]', 'kids', nil, :id => "c3" ) %>
              <label for="c3"><span>Kid's</span></label>
            </div>

            <div class="radioCheckWrap">
              <%= check_box_tag('q[subcategory_in][]', 'sunglasses', nil, :id => "c4" ) %>
              <label for="c4"><span>Sun Glasses</span></label>
            </div>
          </li>
          <li data-legend="Frames">
            <div class="radioCheckWrap">
              <%= check_box_tag('q[frames_in][]', 'half rim', nil, :id => "c5" ) %>
              <label for="c5"><span>Half Rim</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[frames_in][]', 'full rim', nil, :id => "c6" ) %>
              <label for="c6"><span>Full Rim</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[frames_in][]', 'rimless', nil, :id => "c7" ) %>
              <label for="c7"><span>Rimless</span></label>
            </div>
          </li>
          <li data-legend="Shapes">
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'aviator', nil, :id => "c8" ) %>
              <label for="c8"><span>Aviator</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'rectangle', nil, :id => "c9" ) %>
              <label for="c9"><span>Rectangle</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'oval', nil, :id => "c10" ) %>
              <label for="c10"><span>Oval</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'sheild', nil, :id => "c11" ) %>
              <label for="c11"><span>Shield</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'wayfarer', nil, :id => "c12" ) %>
              <label for="c12"><span>Wayfarer</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'cat', nil, :id => "c13" ) %>
              <label for="c13"><span>Cat</span></label>
            </div>
          </li>
          <li data-legend="Material">
            <div class="radioCheckWrap">
              <%= check_box_tag('q[material_in][]', 'titanium', nil, :id => "c14" ) %>
              <label for="c14"><span>Titanium</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'plastic', nil, :id => "c15" ) %>
              <label for="c15"><span>Plastic</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'metal', nil, :id => "c16" ) %>
              <label for="c16"><span>Metal</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'wood', nil, :id => "c17" ) %>
              <label for="c17"><span>Wood</span></label>
            </div>
          </li>
          <li data-legend="Size">
            <div class="radioCheckWrap">
              <%= check_box_tag('q[size_in][]', 'small', nil, :id => "r1" ) %>
              <label for="r1"><span>Small</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'medium', nil, :id => "r2" ) %>
              <label for="r2"><span>Medium</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[shapes_in][]', 'large', nil, :id => "r3" ) %>
              <label for="r3"><span>Large</span></label>
            </div>
          </li>

          <li data-legend="Color">
            <div class="colorPallete">
              <div>
                <%= check_box_tag('q[color_in][]', 'fallgreen', nil,class: 'checkbox-inline', :id => "co_col_1" ) %>
                <a onclick="select_prev_check(id='color1')"  id="color1" href="javascript:"><span class="filterColor fallGreen"></span></a>
                <%= check_box_tag('q[color_in][]', 'black', nil,class: 'checkbox-inline', :id => "co_col_2" ) %>
                <a onclick="select_prev_check(id='color2')" id="color2" href="javascript:"><span class="filterColor black"></span></a>
                <%= check_box_tag('q[color_in][]', 'gray', nil,class: 'checkbox-inline', :id => "co_col_3" ) %>
                <a onclick="select_prev_check(id='color3')" id="color3" href="javascript:"><span class="filterColor gray"></span></a>
              </div>
              <div>
                <%= check_box_tag('q[color_in][]', 'blue', nil,class: 'checkbox-inline', :id => "co_col_4" ) %>
                <a onclick="select_prev_check(id='color4')" id="color4" href="javascript:"><span class="filterColor blue"></span></a>
                <%= check_box_tag('q[color_in][]', 'buddhagold', nil,class: 'checkbox-inline', :id => "co_col_5" ) %>
                <a onclick="select_prev_check(id='color5')" id="color5" href="javascript:"><span class="filterColor buddhaGold"></span></a>
                <%= check_box_tag('q[color_in][]', 'totempole', nil,class: 'checkbox-inline', :id => "co_col_6" ) %>
                <a onclick="select_prev_check(id='color6')" id="color6" href="javascript:"><span class="filterColor totemPole"></span></a>
              </div>
              <div>
                <%= check_box_tag('q[color_in][]', 'eggplant', nil,class: 'checkbox-inline', :id => "co_col_7" ) %>
                <a onclick="select_prev_check(id='color7')" id="color7" href="javascript:"><span class="filterColor eggPlant"></span></a>
                <%= check_box_tag('q[color_in][]', 'pink', nil,class: 'checkbox-inline', :id => "co_col_8" ) %>
                <a onclick="select_prev_check(id='color8')" id="color8" href="javascript:"><span class="filterColor pink"></span></a>
                <%= check_box_tag('q[color_in][]', 'copper', nil,class: 'checkbox-inline', :id => "co_col_9" ) %>
                <a onclick="select_prev_check(id='color9')" id="color9" href="javascript:"><span class="filterColor copper"></span></a>
              </div>
              <div>
                <%= check_box_tag('q[color_in][]', 'white', nil,class: 'checkbox-inline', :id => "co_col_10" ) %>
                <a onclick="select_prev_check(id='color10')" id="color10" href="javascript:"><span class="filterColor white"></span></a>
                <%= check_box_tag('q[color_in][]', 'yellow', nil,class: 'checkbox-inline', :id => "co_col_11" ) %>
                <a onclick="select_prev_check(id='color11')" id="color11" href="javascript:"><span class="filterColor yellow"></span></a>
                <%= check_box_tag('q[color_in][]', 'titan', nil,class: 'checkbox-inline', :id => "co_col_12" ) %>
                <a onclick="select_prev_check(id='color12')" id="color12" href="javascript:"><span class="filterColor titan"></span></a>
              </div>
              <div>
                <%= check_box_tag('q[color_in][]', 'orange', nil,class: 'checkbox-inline', :id => "co_col_13" ) %>
                <a onclick="select_prev_check(id='color13')" id="color13" href="javascript:"><span class="filterColor orange"></span></a>
                <%= check_box_tag('q[color_in][]', 'brown', nil,class: 'checkbox-inline', :id => "co_col_14" ) %>
                <a onclick="select_prev_check(id='color14')" id="color14" href="javascript:"><span class="filterColor brown"></span></a>
                <%= check_box_tag('q[color_in][]', 'fallgreen', nil,class: 'checkbox-inline', :id => "co_col_15" ) %>
                <a onclick="select_prev_check(id='color15')" id="color15" href="javascript:"><span class="filterColor doveGray"></span></a>
              </div>
            </div>
          </li>
          <li data-legend="RX Type">
            <div class="radioCheckWrap">
              <%= check_box_tag('q[rx_type_in][]', 'single vision', nil, :id => "c18" ) %>
              <label for="c18"><span>Single Vision</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[rx_type_in][]', 'bifocal', nil, :id => "c19" ) %>
              <label for="c19"><span>Bifocal</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[rx_type_in][]', 'progressive', nil, :id => "c20" ) %>
              <label for="c20"><span>Progessive</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[rx_type_in][]', 'high definition', nil, :id => "c21" ) %>
              <label for="c21"><span>High Definition</span></label>
            </div>
            <div class="radioCheckWrap">
              <%= check_box_tag('q[rx_type_in][]', 'non prescription', nil, :id => "c22" ) %>
              <label for="c22"><span>Non Prescription</span></label>
            </div>
          </li>
        </ul>
        <div class="filterBtns">
          <a onclick="openPage_clear()" href="javascript:" class="btn btn-info">Reset</a>
          <%= f.submit "filter", class: "btn btn-info" %>
        </div>

      </div>
     <!-- <a onclick="openPage_clear()" href="javascript:"  class="btn btn-lg btn-primary filter-button">clear</a>
      <%= f.submit "filter", class: "btn btn-lg btn-primary filter-button" %> -->
    <% end %>

      <!--<div class="collapseArrow">-->
      <!--<a href="javascript:"><i class="fa fa-angle-up"></i></a>-->
      <!--</div>-->
    </div>

  </div>

  <div class="filterByTypeWrapper">
    <section class="glassesShowCase">
      <div class="container productContainer">
        <div class="clearfix titleWrapper">
          <h3 class="pull-left"><%= @page_title %></h3>
          <span class="sortFilter pull-right">
                        <select id="changer" class="form-control">
                            <option value="asc">Price upto High</option>
                            <option value="dec">Price upto Low</option>
                        </select>
                    </span>
          <div class="border-bg"></div>
        </div>

        <div id="filterrific_results">
        <div class="row">
          <% for product in @products %>
            <div class="col-md-3">
              <div class="glassInfoWrap">
                <h4 class="list-group-item-heading"></h4>
                <span class="price"><%= number_to_currency(product.price) %></span>

                <%= link_to product,  { 'data-toggle' => "tooltip", 'data-placement' => "top", 'data-original-title' => product.name, 'data-method' => 'get' }  do %>
                  <%= image_tag(product.avatar, :class => "img-responsive") %>
                <% end %>

                <div class="ratingSocialWrap">
                  <%= text_field_tag product.id, product.rating, class: 'custum-star-rating' %>
                  <span class="socialWrap">

                      <% if not @fav_list %>

                      <%= link_to favorites_product_path(product), method: :post, :remote => true do %>
                        <i class="fa fa-heart" aria-hidden="true"></i>
                      <% end %>

                      <% end %>

                        <%= link_to prescription_path(:product => product.id), method: :get do %>
                          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        <% end %>
                  </span>
                </div>
              </div>
            </div>
          <% end %>
        </div>
          </div>
        <%= will_paginate @products %>
      </div>
      <div class='scrolltop'>
        <div class='scroll icon'><i class="fa fa-4x fa-angle-up"></i></div>
      </div>
    </section>
  </div>
</div>

app/views/products/new.html.erb
<h1>Create a new Product</h1>
<%= render 'form', product: @product %>

app/views/products/paginate.js.erb
//$('.productContainer').append('<%= j render 'products/show' %>');
<% if @products.next_page %>
$('.productContainer').append('<%= j render 'products/show' %>');
<% else %>
$(window).off('scroll');
$('.pagination').remove();
<% end %>

app/views/products/show.html.erb
<div class="container">
  <%= render 'products/product' %>
</div>