config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get 'review/index'

  get 'home/index'

  get 'checkout/new'

  devise_for :customers, :controllers => { registrations: 'registrations' }

  root 'home#index'
  get '/help-center' => 'home#helpcenter'
  get '/return-policy' => 'home#returnpolicy'


  resources :products do
    member do
      post 'favorites', to: 'products#add_to_favorites'
    end
    collection do
      get 'favorites'
    end
    resources :reviews, only: [:index, :create], defaults: {format: :json}
  end
  resources :order_lines, only: [:create, :update, :destroy]
  resource :checkouts, only: [:new, :create, :update]

  get 'prescription' => 'lens#enter_pre'
  get 'select_lens' => 'lens#select_len'
  get 'cities' => 'checkouts#cities'
  post 'prescription/create' => 'lens#create'
  patch 'prescription/update' => 'lens#update'
  patch 'prescription/update_pre' => 'lens#update_pre'
  delete 'prescription/destroy' => 'lens#destroy'


  get 'cart' => 'carts#show'
  get 'carts' => 'carts#index'

  get 'card' => 'checkouts#credit_card_info'
  post 'process_card' => 'checkouts#process_credit_card'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="Ali-Kazmi">

  <title>110Glasses</title>

  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <%=  stylesheet_link_tag "star-rating.min" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>


  <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag "slick.min" %>

  <%= javascript_include_tag "select2.min" %>

  <%= javascript_include_tag "nouislider.min" %>





  <link rel="stylesheet" href="https://mbraak.github.io/jqTree/jqtree.css" />
  <script src="https://mbraak.github.io/jqTree/tree.jquery.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
<!--
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">CrossOver</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if customer_signed_in? %>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Order List', carts_path %></li>
            <li><%= link_to 'Add a new product', new_product_path %></li>
            <li><%= link_to "#{ current_order.order_lines.size }  Cart", cart_path %></li>
            <li><%= link_to('Logout', destroy_customer_session_path, :method => :delete) %></li>
        <% else %>
              <li><%= link_to('Login', new_customer_session_path)  %></li>
              <li><%= link_to('Register', new_customer_registration_path)  %></li>
         <% end %>
      </ul>
    </div>
  </div>
</nav>

<% flash.each do |key, value| %>
    <div class="message">
      <div class="alert alert-<%= key %>" role="alert">
        <a class="close" href="#">&times</a>
        <strong><%= value %></strong>
      </div>
    </div>
<% end %>
-->

<header>
  <%= search_form_for @q , url: products_path do |f| %>
  <div class="topnav clearfix">
    <div class="container">
      <span class="tollNumber"></span>
      <% if current_page?(card_path) %>
          <div style="margin-right: 15px" class="searchSignIn pull-left">
            <div class="htSearchField">
              <i style="margin-right: 5px" class="fa fa-truck" aria-hidden="true"></i>
              Free Shipping
            </div>
            <div class="htSearchField" style="margin-left: 15px">
              <i style="margin-right: 5px" class="fa fa-undo" aria-hidden="true"></i>
              100 Day Return
            </div>
            <!-- <span>Track Order</span> -->
            <!-- <span>Sign in</span> -->
          </div>
      <% else %>
          <div style="margin-right: 15px" class="searchSignIn pull-right">
            <div class="htSearchField">
              <%= f.search_field :name_cont, class: "form-control" %>

              <span class="fa fa-search"></span>
            </div>
            <!-- <span>Track Order</span> -->
            <!-- <span>Sign in</span> -->
          </div>
      <% end %>

    </div>
  </div>
  <% end %>
  <nav class="navbar navbar-cus">
    <div class="container clearfix">

      <div class="navbar-header">
        <div id="hamBurgerIcon">
          <!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">-->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
            <span></span>
            <span></span>
            <span></span>
          </button>
        </div>

        <a onclick="openPage()"  class="navbar-brand" href="#">
          <h2>110glasses</h2>
        </a>
      </div>
      <% if not current_page?(card_path) %>
      <div class="collapse navbar-collapse" id="navigation">
        <div class="clearfix">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a onclick="openPage_mens()" href="#" data-toggle="dropdown" class="dropdown-toggle">Men</a>
              <ul class="dropdown-menu">
                <li>
                  <a onclick="openPage_mens_eyeglasses()" href="#">Eyeglasses</a>
                </li>
                <li>
                  <a onclick="openPage_mens_preglasses()" href="#">Premium Eyeglasses</a>
                </li>
                <li>
                  <a onclick="openPage_mens_sunglasses()" href="#">Sunglasses</a>
                </li>
                <li>
                  <a onclick="openPage_mens_powerglasses()" href="#">Power Sunglasses</a>
                </li>
                <li>
                  <a href="javascript:">Contact lenses</a>
                </li>
              </ul>
            </li>
            <li>
              <a onclick="openPage_womens()" href="#">Women</a>
            </li>
            <li>
              <a onclick="openPage_kids()" href="#">Kids</a>
            </li>
           <!-- <li><a href="javascript:">Sun Glasses</a>
            </li> -->
            <li class="dropdown">
              <a onclick="openPage_helpcenter()" href="javascript:">Help Center</a>
              <ul class="dropdown-menu">
                <li>
                  <a onclick="openPage_return_policy()" href="#">Return Policy</a>
                </li>
              </ul>
            </li>
            <li>
              <a onclick="openPage_wishlist()" href="javascript:">Wish list</a>
            </li>
            <li>
              <a id="cartclick" href="javascript:"><i class="fa fa-shopping-cart"></i> Cart <span class="badge"><%=@order.presciptions.count %></span></a>
            </li>
          </ul>
        </div>
      </div>
      <% end %><!--.nav-collapse -->
    </div>
  </nav>



  <!--navbar end-->
</header>
<!--header end-->

<div class="container2" style="z-index: 1080">
  <div class="shopping-cart" style="z-index: 1080">
    <div class="shopping-cart-header">
      <i class="fa fa-shopping-cart cart-icon"></i><span class="badge"><%=@order.presciptions.count %></span>
      <div class="shopping-cart-total">
        <span class="lighter-text">Total:</span>
        <span class="main-color-text">$<%= @order.total %></span>
      </div>
    </div> <!--end shopping-cart-header -->

    <% if @order.presciptions.empty? %>

        <div class="selectLensWrap cartDTextWrap">
          <h3>No Products in the cart</h3>
        </div>

    <% else %>

        <ul class="shopping-cart-items">

          <% for pre in @order.presciptions %>
              <% if pre.product %>
              <li class="clearfix2">
                <div>
                <%= image_tag(pre.product.avatar, class: 'shopping-img') %>
                </div>
                <div class="shopping-details">
                <span class="item-name"><%= pre.product.name %></span>
                <span class="item-price">$<%= pre.total_cost %></span>
                <span class="item-quantity">Quantity: <%= pre.qty %></span>
                </div>
              </li>
              <% end %>
          <% end %>
        </ul>
        <%= link_to "Checkout", new_checkouts_path, method: :get, class: "button" %>
        <%= link_to "View Cart", cart_path, method: :get, class: "button-cart" %>

    <% end %>


  </div> <!--end shopping-cart -->
</div>

<%= yield %>

<!--footer start-->
<footer>
  <div class="container">
    <div class="clearfix">
      <div class="contactDetails">
        <h2>110Glasses</h2>
        <span>
                <i class="support_icon call"></i>
                1-800-832-5076
            </span>
        <span>
                <i class="support_icon phone"></i>
                0000 000 000
            </span>
        <span>
                <i class="support_icon mail"></i>
                info@marveloptics.com
            </span>
      </div>
      <div class="footerNav">
        <ul>
          <li>
            <a onclick="openPage_mens()" href="#">Men</a>
          </li>
          <li>
            <a onclick="openPage_womens()" href="#">Women</a>
          </li>
          <li>
            <a onclick="openPage_kids()" href="#">Kids</a>
          </li>
          <li>
            <a onclick="openPage_wishlist()" href="javascript:">Wish list</a>
          </li>
          <li>
            <a onclick="openPage_helpcenter()" href="javascript:">Help Center</a>
          </li>
        </ul>
        <div class="subscribeWrap">
          <label>Subscribe</label>
          <div class="subInput">
            <input type="text" class="form-control" placeholder="Email">
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="copyRightWrap clearfix">

    </div>
  </div>
</footer>
<!-- js-social jquery plugin -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.jssocials/1.4.0/jssocials.min.js"></script>
<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.jssocials/1.4.0/jssocials.css" />
<link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/jquery.jssocials/1.4.0/jssocials-theme-classic.css" />

</body>

<%= javascript_include_tag "nouislider.min" %>
</html>